import type { Metadata } from "next";
import "./globals.css";

import TopNavbar from "./components/Topnarbar";
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext"; // ✅ เพิ่มตรงนี้

import GlobalAuthGuard from "./components/GlobalAuthChecker";

export const metadata: Metadata = {
  title: "BuriThaiTeam Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* ✅ ห่อด้วย CartProvider ครอบทั้ง app */}
        <CartProvider>
          <GlobalAuthGuard />
          <header className="fixed top-0 left-0 right-0 z-[1000] bg-white border-b border-gray-200 dark:bg-gray-900 dark:border-gray-700">
            <TopNavbar />
          </header>
          <main className="pt-[120px] sm:pt-[100px] md:pt-[170px]">
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </CartProvider>
      </body>
    </html>
  );
}
