import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import TopNavbar from "./components/Topnarbar";
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext"; // ✅ เพิ่มตรงนี้

// import GlobalAuthGuard from "./components/GlobalAuthChecker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BuriThaiTeam Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {/* ✅ ห่อด้วย CartProvider ครอบทั้ง app */}
        <CartProvider>
          {/* <GlobalAuthGuard />    */}
          <header className="sticky top-0 z-50 bg-white border-b border-gray-200 dark:bg-gray-900 dark:border-gray-700">
            <TopNavbar />
          </header>
          <main>
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </CartProvider>
      </body>
    </html>
  );
}
